# Generated by Django 5.0.6 on 2024-06-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_id_club_event_eventattendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='members',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.AlterField(
            model_name='club',
            name='president',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presided_club', to='main.student'),
        ),
        migrations.CreateModel(
            name='ClubStudents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.club')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
